version: "3.9"

services:
  postgres-test:
    image: postgres:16
    container_name: employee-management-test-db
    environment:
      POSTGRES_DB: employee_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - employee-test-net

  employee-management-test:
    container_name: employee-management-test
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-test:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: test

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-test:5432/employee_test
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test_password

      JAVA_TOOL_OPTIONS: >
        -Xms128m
        -Xmx256m
        -XX:+UseG1GC

    volumes:
      - ./uploads:/app/uploads

    command: ["java", "-jar", "/app/app.jar"]

    networks:
      - employee-test-net

networks:
  employee-test-net:
    driver: bridge
